- alias: Remote kraftig lys
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"state": "group on", "entity_id": "switch.nexa_remote"}
  action:
    - service: scene.turn_on
      entity_id: scene.kraftig_lys

- alias: Remote dempet lys
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"state": "group off", "entity_id": "switch.nexa_remote"}
  action:
    - service: scene.turn_on
      entity_id: scene.dempet_lys

- alias: Door bad closing
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"state": "unknown command (0x9da790)", "entity_id": "switch.door_closing_1"}
    - platform: event
      event_type: button_pressed
      event_data: {"state": "unknown command (0x900620)", "entity_id": "switch.door_closing_2"}
  action:
   - service: homeassistant.turn_off
     entity_id: input_boolean.door_bad

- alias: Door bad opening
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"state": "unknown command (0x98e2b0)", "entity_id": "switch.door_opening_1"}
    - platform: event
      event_type: button_pressed
      event_data: {"state": "unknown command (0x9bbd40)", "entity_id": "switch.door_opening_2"}
  action:
   - service: homeassistant.turn_on
     entity_id: input_boolean.door_bad

- alias: Turn off lights at night
  trigger:
    - platform: time
      after: '23:40:00'
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: Turn on lights before sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.kraftig_lys

- alias: Demp lys kveld
  trigger:
    - platform: sun
      event: sunset
      offset: '+01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.dempet_lys

- alias: Alle borte
  trigger:
    - platform: state
      entity_id: group.tracker
      from: 'home'
      to: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: Good morning
  trigger:
    - platform: time
      after: 07:30
  condition:
    - condition: time
      weekday: [mon, tue, wed, thu, fri]
  action:
    - service: media_player.turn_on
      entity_id: media_player.argon_inet2_002261edde0a
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: Argon iNet2+ 002261edde0a
    - service: media_player.volume_set
      data:
        entity_id: media_player.argon_inet2_002261edde0ame
        volume_level: 0.6
    - service: media_player.play_media
      data:
        entity_id: media_player.spotify
        media_content_type: playlist
        media_content_id: spotify:user:spotify:playlist:37i9dQZF1DX1j96SzHv3js
