- alias: Remote kraftig lys
  initial_state: True
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"state": "group on", "entity_id": "switch.nexa_remote"}
  action:
    - service: scene.turn_on
      entity_id: scene.kraftig_lys

- alias: Remote dempet lys
  initial_state: True
  trigger:
    - platform: event
      event_type: button_pressed
      event_data: {"state": "group off", "entity_id": "switch.nexa_remote"}
  action:
    - service: scene.turn_on
      entity_id: scene.dempet_lys

- alias: Turn off lights at night
  initial_state: True
  trigger:
    - platform: time
      at: '23:40:00'
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: Turn on lights before sunset
  initial_state: True
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.kraftig_lys

- alias: Demp lys kveld
  initial_state: True
  trigger:
    - platform: sun
      event: sunset
      offset: '+01:00:00'
  action:
    service: scene.turn_on
    entity_id: scene.dempet_lys

- alias: Alle borte
  initial_state: True
  trigger:
    - platform: state
      entity_id: group.tracker
      from: 'home'
      to: 'not_home'
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: Good morning
  initial_state: False
  trigger:
    - platform: time
      at: 07:30
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: media_player.turn_on
      entity_id: media_player.argon_inet2_002261edde0a
    - service: media_player.select_source
      data:
        entity_id: media_player.spotify
        source: Argon iNet2+ 002261edde0a
    - service: media_player.play_media
      data:
        entity_id: media_player.spotify
        media_content_type: playlist
        media_content_id: spotify:user:spotify:playlist:37i9dQZF1DX1j96SzHv3js
    - service: media_player.volume_set
      data:
        entity_id: media_player.spotify
        volume_level: 0.4

- alias: Nilia hjemme fra skolen
  initial_state: False
  trigger:
    - platform: state
      entity_id: device_tracker.niliasiphone
      to: home
  condition:
    - condition: time
      after: '13:00:00'
      before: '15:00:00'
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: notify.push
      data:
        title: Nilia
        message: Er hjemme

- alias: Turn on living room lights when there is movement
  initial_state: False
  trigger:
    platform: state
    entity_id: binary_sensor.sn1_motion
    to: 'motion detected'
  condition:
    - condition: state
      entity_id: group.livingroom
      state: 'off'
  action:
    service: scene.turn_on
    entity_id: scene.dempet_lys

- alias: Turn off light after last movement at night
  initial_state: False
  trigger:
    platform: state
    entity_id: binary_sensor.sn1_motion
    to: 'standby'
    for:
      minutes: 10
  condition:
    - condition: time
      after: '23:30:00'
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: Hall lights, on
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.gang_sensor
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.taklys_gang_level

- alias: Hall lights, off
  initial_state: True
  trigger:
    platform: state
    entity_id: binary_sensor.gang_sensor
    to: 'off'
    for:
      minutes: 10
  action:
    service: light.turn_off
    entity_id: light.taklys_gang_level

- alias: Basseng, renseanlegg on
  initial_state: False
  trigger:
    - platform: state
      entity_id: sensor.pool_temperature
    - platform: state
      entity_id: input_number.pool_temp_min
  condition:
    - condition: template
      value_template: '{{ float(states("sensor.pool_temperature")) < float(states("input_number.pool_temp_min")) }}'
  action:
    service: switch.turn_on
    entity_id: switch.veggplugg_1_switch

- alias: Basseng, renseanlegg off
  initial_state: False
  trigger:
    - platform: state
      entity_id: sensor.pool_temperature
    - platform: state
      entity_id: input_number.pool_temp_max
  condition:
    - condition: template
      value_template: '{{ float(states("sensor.pool_temperature")) >= float(states("input_number.pool_temp_max")) }}'
  action:
    service: switch.turn_off
    entity_id: switch.veggplugg_1_switch

- alias: Basseng tidsstyring, start
  initial_state: False
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.pool_start_at.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    service: switch.turn_on
    entity_id: switch.veggplugg_1_switch

- alias: Basseng tidsstyring, stopp
  initial_state: False
  trigger:
    platform: template
    value_template: "{{ states('sensor.time') == (states.input_datetime.pool_end_at.attributes.timestamp | int | timestamp_custom('%H:%M', False)) }}"
  action:
    service: switch.turn_off
    entity_id: switch.veggplugg_1_switch
