- platform: mqtt
  state_topic: "hass/sensornode1"
  name: "SN1 Motion"
  device_class: "motion"
  payload_on: "motion detected"
  payload_off: "standby"
  value_template: '{{ value_json.motion }}'

- platform: rfxtrx
  automatic_add: True
  devices:
    0a14110900017f01010070:
      name: Bathroom upstairs
