- platform: template
  sensors:
    door_bad:
      friendly_name: "Badedør oppe"
      value_template: "{{ states.input_boolean.door_bad.state == 'on' }}"
      device_class: opening
      entity_id: input_boolean.door_bad

- platform: mqtt
  state_topic: "hass/sensornode1"
  name: "SN1 Motion"
  device_class: "motion"
  payload_on: "motion detected"
  payload_off: "standby"
  value_template: '{{ value_json.motion }}'
