- platform: template
  sensors:
    door:
      friendly_name: "Ytterdør"
      value_template: "{{ states.input_boolean.door.state == 'on' }}"
      sensor_class: opening
      entity_id: input_boolean.door
