homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml


frontend:
config:
ios:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

scene:
  - name: Natt
    entities:
      group.all_lights:
        state: off
      switch.bryter_1:
        state: off
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch_4_0:
        state: off

  - name: Dempet lys
    entities:
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch_4_0:
        state: off
      switch.bryter_1:
        state: off
      light.fibaro_system_fgd212_dimmer_2_level_6_0:
        state: on
        brightness: 40
      light.hue_ambiance_lamp_2:
        brightness: 80
        color_temp: 500
        state: on

  - name: Kraftig lys
    entities:
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch_4_0:
        state: on
      switch.bryter_1:
        state: on
      light.fibaro_system_fgd212_dimmer_2_level_6_0:
        state: on
        brightness: 100
      light.hue_ambiance_lamp_2:
        brightness: 100
        color_temp: 300
        state: on

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

switch: !include switches.yaml
automation: !include automation.yaml
sensor: !include_dir_list sensors/
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
#device_tracker: !include device_tracker.yaml

# Text to speech
tts:
  platform: google

group: !include groups.yaml

notify:
  - name: push
    platform: pushbullet
    api_key: !secret pb_apikey

zwave:
  usb_path: /dev/ttyACM1
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
  debug: True

rfxtrx:
  device: /dev/ttyUSB1
  debug: True

mqtt:
  broker: 192.168.0.218
  port: 1883
  client_id: hass
  username: rudolfsen
  password: !secret mqtt_password
