homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

scene:
  - name: Natt
    entities:
      group.all_lights:
        state: off
      switch.bryter_1:
        state: off
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch_4_0:
        state: off

  - name: Dempet lys
    entities:
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch_4_0:
        state: off
      switch.bryter_1:
        state: off
      light.fibaro_system_fgd212_dimmer_2_level_6_0:
        state: on
        brightness: 40
      light.hue_ambiance_lamp_2:
        brightness: 80
        color_temp: 500
        state: on

  - name: Kraftig lys
    entities:
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch_4_0:
        state: on
      switch.bryter_1:
        state: on
      light.fibaro_system_fgd212_dimmer_2_level_6_0:
        state: on
        brightness: 100
      light.hue_ambiance_lamp_2:
        brightness: 100
        color_temp: 300
        state: on

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor: !include_dir_list sensors/

# Text to speech
tts:
  platform: google

group: !include groups.yaml

notify:
  - name: push
    platform: pushbullet
    api_key: !secret pb_apikey

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
  debug: True

rfxtrx:
  device: /dev/ttyUSB1
  debug: True

switch:
  platform: rfxtrx
  automatic_add: True
  signal_repetitions: 2
  devices:
    0710010f4f080750:
      name: Bryter 1
      fire_event: True
    071001014e080760:
      name: Bryter 2
      fire_event: True
    071001204c080750:
      name: Bryter 3
      fire_event: True
    0710010248080740:
      name: Remote btn 4A
      fire_event: True
    07100a0041010000:
      name: RA1
      fire_event: True
    0b11000b016bda9a01010f60:
      name: Nexa remote
      fire_event: True
    091300039da790017770:
      name: Door closing 1
      fire_event: True
    09130006900620017770:
      name: Door closing 2
      fire_event: True
    0913000098e2b0017a70:
      name: Door opening 1
      fire_event: True
    091300049bbd40017770:
      name: Door opening 2
      fire_event: True

automation:
  - alias: Remote kraftig lys
    trigger:
      - platform: event
        event_type: button_pressed
        event_data: {"state": "group on", "entity_id": "switch.nexa_remote"}
    action:
      - service: scene.turn_on
        entity_id: scene.kraftig_lys

  - alias: Remote dempet lys
    trigger:
      - platform: event
        event_type: button_pressed
        event_data: {"state": "group off", "entity_id": "switch.nexa_remote"}
    action:
      - service: scene.turn_on
        entity_id: scene.dempet_lys

  - alias: Door closing
    trigger:
      - platform: event
        event_type: button_pressed
        event_data: {"state": "unknown command (0x9da790)", "entity_id": "switch.door_closing_1"}
      - platform: event
        event_type: button_pressed
        event_data: {"state": "unknown command (0x900620)", "entity_id": "switch.door_closing_2"}
    action:
      - service: scene.turn_on
        entity_id: scene.dempet_lys

  - alias: Door opening
    trigger:
      - platform: event
        event_type: button_pressed
        event_data: {"state": "unknown command (0x98e2b0)", "entity_id": "switch.door_opening_1"}
      - platform: event
        event_type: button_pressed
        event_data: {"state": "unknown command (0x9bbd40)", "entity_id": "switch.door_opening_2"}
    action:
      - service: notify.push
        data:
          message: "Dør åpnet seg"
