homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

scene:
  - name: Natt
    entities:
      group.all_lights:
        state: off
      switch.bryter_1:
        state: off

  - name: Dempet lys
    entities:
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch_4_0:
        state: off
      switch.bryter_1:
        state: off
      light.fibaro_system_fgd212_dimmer_2_level_6_0:
        state: on
        brightness: 40
      light.hue_ambiance_lamp_2:
        brightness: 80
        color_temp: 500
        state: on

  - name: Kraftig lys
    entities:
      switch.fibaro_system_fgwpef_wall_plug_gen5_switch_4_0:
        state: on
      switch.bryter_1:
        state: on
      light.fibaro_system_fgd212_dimmer_2_level_6_0:
        state: on
        brightness: 100
      light.hue_ambiance_lamp_2:
        brightness: 100
        color_temp: 300
        state: on

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

sensor: !include_dir_list sensors/

# Text to speech
tts:
  platform: google

group: !include groups.yaml

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
  debug: true

rfxtrx:
  device: /dev/ttyUSB1

switch:
  platform: rfxtrx
  automatic_add: True
  devices:
    0710010f4f080750:
      name: Bryter 1
    071001014e080760:
      name: Bryter 2
    071001204c080750:
      name: Bryter 3
