homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml

frontend:
config:
ios:

http:
  api_password: !secret http_password
  base_url: !secret http_base_url
  ssl_certificate: !secret ssl_cert_path
  ssl_key: !secret ssl_key_path
  trusted_networks:
   - 127.0.0.1
   - 192.168.0.0/24

updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

climate:
  platform: zwave

switch: !include switches.yaml
automation: !include automation.yaml
sensor: !include_dir_list sensors/
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
scene: !include_dir_list scenes/
device_tracker: !include device_tracker.yaml

# Text to speech
tts:
  platform: google

group: !include groups.yaml

notify:
  - name: push
    platform: pushbullet
    api_key: !secret pb_apikey
  - name: html5
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/lib/python3.4/site-packages/python_openzwave/ozw_config
  debug: False

rfxtrx:
  device: /dev/ttyUSB1
  debug: False

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
  - platform: samsungtv
    name: TV, stue
    host: 192.168.0.148
    mac: 78:AB:BB:D4:F1:EF
  - platform: panasonic_viera
    name: TV, peisestue
    host: 192.168.0.121
    mac: A8:13:74:4B:67:D4

mqtt:
  broker: 192.168.0.218
  port: 1883
  client_id: hass
  username: rudolfsen
  password: !secret mqtt_password
