homeassistant:
  name: Home
  latitude: !secret home_lat
  longitude: !secret home_long
  elevation: !secret home_elevation
  unit_system: metric
  time_zone: Europe/Oslo
  customize: !include customize.yaml


frontend:
config:
ios:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

switch: !include switches.yaml
automation: !include automation.yaml
sensor: !include_dir_list sensors/
binary_sensor: !include binary_sensor.yaml
input_boolean: !include input_boolean.yaml
scene: !include_dir_list scenes/
device_tracker: !include device_tracker.yaml

# Text to speech
tts:
  platform: google

group: !include groups.yaml

notify:
  - name: push
    platform: pushbullet
    api_key: !secret pb_apikey

zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/homeassistant/src/python-openzwave/openzwave/config
  debug: True

rfxtrx:
  device: /dev/ttyUSB1
  debug: True

media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret

#mqtt:
#  broker: 192.168.0.218
#  port: 1883
#  client_id: hass
#  username: rudolfsen
#  password: !secret mqtt_password
